apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: eval
  labels:
    app: fastapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: ktchl/k8s-dst-eval-fastapi:latest
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "8000","--log-level", "debug"]
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
          - name: MYSQL_PORT
            value: "3307"
          - name: MYSQL_HOST
            value: "mysql-service-clusterip.eval.svc.cluster.local"
        envFrom:
          - secretRef:
              name: mysql-user
        ports:
          - containerPort: 8000