apiVersion: v1
kind: Service
metadata:
  name: monnodeport
  namespace: eval
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000