apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kenny
  namespace: eval
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: eval
    name: pvc-kenny-mysql-0 
  hostPath:
    path: "/home/ubuntu/eval/data"

