apiVersion: v1
kind: Service
metadata:
  name: mysql-service-clusterip
  namespace: eval
spec:
  type: ClusterIP
  selector:
    app: mysql 
  ports:
    - protocol: TCP
      port: 3307        
      targetPort: 3306 
  clusterIP: 10.43.0.42